# permissions for end users to view ansibleinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ansibleinventory-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: ansibleinventory-viewer-role
rules:
- apiGroups:
  - ansible-operator.ansible-operator.io
  resources:
  - ansibleinventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ansible-operator.ansible-operator.io
  resources:
  - ansibleinventories/status
  verbs:
  - get
