---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ansible-operator.ansible-operator.io
  resources:
  - ansiblejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ansible-operator.ansible-operator.io
  resources:
  - ansiblejobs/finalizers
  verbs:
  - update
- apiGroups:
  - ansible-operator.ansible-operator.io
  resources:
  - ansiblejobs/status
  verbs:
  - get
  - patch
  - update
